### ISSUE TITLE
SUPER COOL!

### ISSUE THREAD

**Issue by geeksville** [meshtastic/meshtastic.js#1]
This project is super cool!  Bravo.  Is it okay for me to add links to it from the main webpage?

Also - if you'd like to put it in the meshtastic github project, I'm happy to add you as a committer there and you can do so.  (but no pressure)

**Comment by thepoweroftwo** [comment]
>  Is it okay for me to add links to it from the main webpage?

Sure, go ahead! :) 

Putting it in the meshtastic github would allow others to find it more easily. I'm open to this idea. How would we manage this - do i recommit everything to a new repo there, that then becomes the "main" one?

**Comment by geeksville** [comment]
Hmm.  I think it works like when I transfered the other repos.  I just added you to our group (github will email you).  You go to settings / transfer repo.  Github will automatically redirect anyone who has already forked the repo.  Then after the transfer you click on fork to bring back a local copy for your dev work.  Then you can use the 'root' copy for whatever you want to release.

Also you might want to do a post in the forum about this cool project.  I heard about it from @mc-hamster but had forgotten to follow up.

![transfer](https://user-images.githubusercontent.com/225513/95797298-03a13b00-0ca4-11eb-8fea-a0858ed13e32.png)

**Comment by thepoweroftwo** [comment]
Aaand.. it's done! Great.
Will do a post on the forum in the coming days.

**Comment by mc-hamster** [comment]
This is so cool!
