### ISSUE TITLE
Implement Web Serial functions

### ISSUE THREAD

**Issue by thepoweroftwo** [meshtastic/meshtastic.js#10]
Make it possible to connect to a meshtastic device via the Web Serial API. 
It is currently in origin trial in chrome. 

https://www.chromestatus.com/feature/6577673212002304

Example:
https://codelabs.developers.google.com/codelabs/web-serial/?hl=iw

Maybe: add a feature to the meshtastic device code so that "autodiscover" works; meaning when you connect the device via usb a notification from the browser pops up that tells the user what to do. (Link to a meshtastic web app under app.meshtastic.org)

**Comment by sachaw** [comment]
Think it would also be good to implement this with a switch in the constructor to specify the serial implementation.
i.e. using WebSerial for browsers or https://serialport.io/ for node.

**Comment by sachaw** [comment]
Origin trials should finish early March, I'm gonna have a look into it around then, as it will be accessible to everyone at that time.

**Comment by sachaw** [comment]
This is now implemented, But lacks node serial support, which will be added later
