### ISSUE TITLE
GATT operation not authorized

### ISSUE THREAD

**Issue by chucknitro** [meshtastic/meshtastic.js#2]
- Running Windows 10 Chrome 
- Latest update of meshtastic.js 
- hw_model: "tlora-v1" with firmware_version: "1.1.5" - NOTE: no screen. I connect via PUTTY to get Bluetooth Pairing Code
- Pair tlora via Windows Bluetooth Add connection.
- Click "Connect" on HTML form
- Select meshtastic device in Chrome pop up
- Error logged to console
```
Error: Error in meshtasticjs.IBLEConnection.connect: Error in meshtasticjs.IMeshDevice.onConnected: GATT operation not authorized.
    at EventTarget.connect (meshtastic.js:formatted:3999)
```

**Comment by thepoweroftwo** [comment]
Oh yeah. I've come across this error before on Windows.
Unfortunately it is beyond the control of the library, this message gets returned by the browser API itself.

What you can try:

- Remove the device from windows bluetooth settings and pair again (if it's not shown there, go to Device Manager, click "View" in the top menu, select "show hidden devices" and then uninstall the device)

- Open the site chrome://bluetooth-internals and try to connect to the device and read from a characteristic from there:
   - Select Devices on the left
   - Click "Start Scan"
   - Find the meshtastic device and click "Inspect"
   - Open the service characteristic with the UUID `6ba1b218-15a8-461f-9fa8-5dcae273eafd`
   - Try to read from `8ba2bcc2-ee02-4a55-a531-c525c5e454d5`, there should appear values other than 0x000000 if you have more than one mesh device running and sending packets
 
- As a last step: Reflash the firmware of your device (maybe it has something to do with bluetooth key store on it)

The web bluetooth API is still kind of experimental, i'll start testing with my devices again.
Let me know what you find, maybe I have overseen something.

**Comment by chucknitro** [comment]
Thanks.  Managed to get passed that error.  

Now I have 

"Error: Error in meshtasticjs.IBLEConnection.connect: Error in meshtasticjs.IMeshDevice.onConnected: Error in meshtasticjs.IBLEConnection.readFromRadio: Error in meshtasticjs.IMeshDevice.handleFromRadio: Error in meshtasticjs.ProtobufHandler.fromProtobuf: invalid wire type 4 at offset 19
    at EventTarget.connect (meshtastic.js:2)"

**Comment by thepoweroftwo** [comment]
> Note the read of 8ba2bcc2-ee02-4a55-a531-c525c5e454d5 show nothing - was expecting to see hex zero.

My bad. I just tried and It seems to return actually nothing if there's no message, not even hex 0.

You can try this special build and pase the console output here, than we have a chance to debug the protocol buffers:
[meshtastic.zip](https://github.com/meshtastic/meshtastic.js/files/5400459/meshtastic.zip)

**Comment by chucknitro** [comment]
Thanks again for your prompt response.

Your zip file worked great.  I went back and downloaded the GIT.  That works!!!!  My bad 👍 

Getting some "fromRadio" events.

**Comment by geeksville** [comment]
yeah - for no message available, we return an empty protobuf (which is zero bytes long)
