### ISSUE TITLE
Build Broken due to changes to to mesh.proto, mesh.options

### ISSUE THREAD

**Issue by gtnoble** [meshtastic/meshtastic.js#59]
https://github.com/meshtastic/Meshtastic-protobufs/commit/e439934e6d8b4675e48a2c053f13564b7cbfa4f7
Removal of location from Data and changing Location name to Waypoint breaks the build. sendLocation is going to need to be reworked to deal with the changes to Data. Do we intend to change sendLocation to use POSITION_APP / WAYPOINT_APP instead of TEXT_MESSAGE_APP?

**Comment by sachaw** [comment]
This is now fixed, thanks.
