### ISSUE TITLE
Changing INodeSerialConnection baud rate

### ISSUE THREAD

**Issue by gtnoble** [meshtastic/meshtastic.js#60]
Should we change the INodeSerialConnection baud rate to 921600? This is what the python CLI app uses for serial connections. I can't connect to the device without changing the baud rate for INodeSerialConnection to 921600. Another possibility is to add a parameter in the constructor to allow the use of different baud rates.

**Comment by thebentern** [comment]
Devices in 1.3 use a fixed 115200 for baud rate for reliability with a lot of the chip shortage USB to serial implementations. 
921600 is the 1.2 legacy default.

**Comment by sachaw** [comment]
fixed

**Comment by sachaw** [comment]
> Should we change the INodeSerialConnection baud rate to 921600? This is what the python CLI app uses for serial connections. I can't connect to the device without changing the baud rate for INodeSerialConnection to 921600. Another possibility is to add a parameter in the constructor to allow the use of different baud rates.

You can already specify a custom baud rate when connecting to a device: https://js.meshtastic.org/interfaces/Types.SerialConnectionParameters.html
